version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  redis:
    image: "redis:alpine"
  celery:
    restart: always
    build: .
    command: celery -A django_page_api worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
