version: '3'
services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
  redis:
    image: "redis:alpine"
  celery:
    restart: always
    build: .
    command: celery -A django_page_api worker -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: