# Generated by Django 4.1 on 2022-08-07 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bitrate', models.IntegerField()),
                ('counter', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'audios',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pages',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('counter', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'texts',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_ulr', models.URLField()),
                ('subtitles_ulr', models.URLField()),
                ('counter', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='PageVideosThroughModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.page')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.video')),
            ],
            options={
                'ordering': ('page', 'order'),
            },
        ),
        migrations.CreateModel(
            name='PageTextThroughModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.page')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.text')),
            ],
            options={
                'ordering': ('page', 'order'),
            },
        ),
        migrations.CreateModel(
            name='PageAudiosThroughModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.audio')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.page')),
            ],
            options={
                'ordering': ('page', 'order'),
            },
        ),
        migrations.AddField(
            model_name='page',
            name='audios',
            field=models.ManyToManyField(through='main.PageAudiosThroughModel', to='main.audio'),
        ),
        migrations.AddField(
            model_name='page',
            name='texts',
            field=models.ManyToManyField(through='main.PageTextThroughModel', to='main.text'),
        ),
        migrations.AddField(
            model_name='page',
            name='videos',
            field=models.ManyToManyField(through='main.PageVideosThroughModel', to='main.video'),
        ),
    ]
